# frozen_string_literal: true

require_relative 'main'
require_relative 'architecture'
require_relative 'architecture_completion'
require_relative 'architecture_validation'
require_relative 'building_elements'
require_relative 'building_elements_validation'
require_relative 'storefront'
require_relative 'storefront_validation'
require_relative 'levels_stairs_roof'
require_relative 'levels_stairs_roof_validation'
require_relative 'advanced_stairs_openings'
require_relative 'advanced_stairs_openings_validation'
require_relative 'model_editing'
require_relative 'auto_repair'
require_relative 'drawing_semantics'
require_relative 'drawing_semantics_validation'
require_relative 'semantic_layout'
require_relative 'semantic_layout_validation'
require_relative 'semantic_grouping'
require_relative 'semantic_grouping_validation'
require_relative 'semantic_group_hierarchy'
require_relative 'semantic_group_hierarchy_validation'
